### ISSUE TITLE
summer-web板块中DispatcherServlet.java文件的参数命名错误

### ISSUE THREAD

**Issue by ChenPi222** [michaelliao/summer-framework#11]
DispatcherServlet类的有参构造器中PropertyResolver参数命名错误，源代码为：
public DispatcherServlet(ApplicationContext applicationContext, PropertyResolver properyResolver)
显然这里第二个参数应为“propertyResolver”，代码中少写了一个字母“t”，虽然对代码运行无影响，但对本项目的严谨性稍有影响，希望可以更正，维持本项目的优雅与完美

（同时非常感谢廖老师这个项目，真的让我学习到了很多~）

**Comment by michaelliao** [comment]
https://github.com/michaelliao/summer-framework/commit/835a4164cf6efc63ba4408e5a526bbdcc2148b8b
