### ISSUE TITLE
对于web-实现MVC部分@RestController和@ResponseBody注解处理的疑问

### ISSUE THREAD

**Issue by ChenPi222** [michaelliao/summer-framework#12]
非常感谢廖老师采纳了我的上一个Issue
本人学艺不精，在实现MVC部分又产生了一些疑问，希望廖老师能拨冗解答

简而言之是Summer框架对@RestController和@ResponseBody注解的处理似乎与Spring不尽相同。
在下面的这段代码中（节选自Dispatcher.java），您对同时具有上述两个注解的结果是采取了直接以字符流或字节流输出到resp的方式，似乎并未考虑结果为Java对象时的情况，结合测试部分代码才发现您在标有@ResponseBody注解的方法中已经先将Java对象转换为JSON格式之后再返回的，尽管能自洽但似乎不够优雅（学艺不精，无意冒犯）。

反观Spring的处理方式，是将@RestController当做@Controller+@ResponseBody来用，即二者的功能和处理手段是相同的，使用者无需在Controller方法的返回值中手动将Java对象转为JSON格式，而是像您这里对没有@ResponseBody注解的结果处理方式一样，直接返回Java对象，由框架统一转JSON格式

```    void doService(String url, HttpServletRequest req, HttpServletResponse resp, List<Dispatcher> dispatchers) throws Exception {
        for (Dispatcher dispatcher : dispatchers) {
            Result result = dispatcher.process(url, req, resp);
            if (result.processed()) {
                Object r = result.returnObject();
                if (dispatcher.isRest) {
                    // send rest response:
                    if (!resp.isCommitted()) {
                        resp.setContentType("application/json");
                    }
                    if (dispatcher.isResponseBody) {
                        if (r instanceof String s) {
                            // send as response body:
                            PrintWriter pw = resp.getWriter();
                            pw.write(s);
                            pw.flush();
                        } else if (r instanceof byte[] data) {
                            // send as response body:
                            ServletOutputStream output = resp.getOutputStream();
                            output.write(data);
                            output.flush();
                        } else {
                            // error:
                            throw new ServletException("Unable to process REST result when handle url: " + url);
                        }
                    } else if (!dispatcher.isVoid) {
                        PrintWriter pw = resp.getWriter();
                        JsonUtils.writeJson(pw, r);
                        pw.flush();
                    }
                } 
```

因此我的建议是与Spring处理方式一致，若有@RestController注解则不再判断是否有@ResponseBody注解，统一转JSON格式写入
再次再次说明，本人学艺不精，如有胡言乱语之处，请廖老师直接忽视即可~

**Comment by michaelliao** [comment]
用@RestController不要用@ResponseBody就可以返回java对象自动转，用ResponseBody视为返回string/byte[]

https://github.com/michaelliao/summer-framework/blob/835a4164cf6efc63ba4408e5a526bbdcc2148b8b/framework/summer-web/src/test/java/com/itranswarp/summer/web/controller/ApiController.java#L34

**Comment by ChenPi222** [comment]
我可能没表达清楚，从用户的角度来说@ResponBody注解对实际工作似乎没有太大作用啊，如果用户想返回java对象还需要手动调用JsonUtils.writeJson()方法将对象转换为JSON格式，那用户使用这个注解的意义在哪里呢？仅仅起到了校验返回值是否为String/byte[]的作用？
从我的角度理解，@Response注解应该实现的功能是，如果用户返回的是java对象，则检测到该注解后Summer框架将对象转换为JSON格式并写入HttpServletResponse，就和@RestController的功能相同，唯一区别是该注解应用于Method，实际Spring中这个注解的功能也是如此。

https://github.com/michaelliao/summer-framework/blob/835a4164cf6efc63ba4408e5a526bbdcc2148b8b/framework/summer-web/src/test/java/com/itranswarp/summer/web/controller/ApiController.java#L30

**Comment by michaelliao** [comment]
正常情况你不需要@Responsebody，但是有可能你想返回redis缓存的json，那就必须返回string：

```
@ResponseBody
String getData() {
    String data = redis.get("xxx");
    if (data==null) {
        data = toJSON(getDataFromDb());
        redis.set("xxx", data);
    }
    return data;
}
```

**Comment by ChenPi222** [comment]
好的老师，可能是我的实际开发经验还很匮乏，过于追求与Spring的一致性，缺少了对实际应用场景的考量。确实大多数情况下@RestController已经够用了，@ResponseBody专注于处理您上述提及的场景就可以
由衷感谢您的耐心答复，也非常感谢您无私分享summer项目~
